import "../../../just/libafl-qemu.just"

FUZZER_NAME := "qemu_baremetal"
VHARNESS     := BUILD_DIR / "vharness_out"

# 1. 指向你已经准备好的 Zephyr ELF
ZEPHYR_ELF := "/home/zxl/zephyr-project/samples/hello_world/build/zephyr/zephyr.elf"
DUMMY_IMG    := TARGET_DIR / "dummy.qcow2"

# 2. 确保目录 & 磁盘镜像
target_dir:
    mkdir -p "{{TARGET_DIR}}"

image: target_dir
    qemu-img create -f qcow2 "{{DUMMY_IMG}}" 32M

# 3. 只编译 LibAFL 侧 fuzzer
build flavor="breakpoint": target_dir
    cargo build \
        --profile {{PROFILE}} \
        --no-default-features \
        --features std,{{flavor}},{{ARCH}} \
        --target-dir {{TARGET_DIR}}

# 4. 修复运行规则
run flavor="breakpoint": image (build flavor)
    env TARGET_DIR="{{TARGET_DIR}}" KERNEL="{{ZEPHYR_ELF}}" \
    {{TARGET_DIR / PROFILE / "qemu_baremetal"}} \
        -icount shift=auto,align=off,sleep=off \
        -machine mps2-an385 \
        -monitor null \
        -kernel "{{ZEPHYR_ELF}}" \
        -drive if=none,format=qcow2,file={{DUMMY_IMG}} \
        -serial null \
        -nographic \
        -snapshot \
        -S

# 5. 修复测试规则
test_flavor flavor="breakpoint": image (build flavor)
    #!/bin/bash
    export KERNEL="{{ZEPHYR_ELF}}"
    export TARGET_DIR="{{TARGET_DIR}}"

    TMP_DIR=$(mktemp -d)

    timeout 10s {{TARGET_DIR / PROFILE / "qemu_baremetal"}} \
        -icount shift=auto,align=off,sleep=off \
        -machine mps2-an385\
        -monitor null \
        -kernel "{{ZEPHYR_ELF}}" \
        -drive if=none,format=qcow2,file={{DUMMY_IMG}} \
        -nographic \
        -snapshot \
        -S | tee "$TMP_DIR/fuzz.log" 2>&1 || true

    if [ -z "$(grep 'Objective' "$TMP_DIR/fuzz.log")" ]; then
        echo "qemu_baremetal ${FEATURE}: Fuzzer did not find the objective in $TMP_DIR/fuzz.log"
        exit 1
    else
        echo "qemu_baremetal ${FEATURE}: Objective found."
    fi

test: (test_flavor "low_level") (test_flavor "breakpoint") (test_flavor "custom_insn")

clean:
    cargo clean